[package]
name = "sis-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"

[dependencies.windows]
version = "0.54.0"
features = [
    "Win32_UI_Input_KeyboardAndMouse",
]
