[package]
name = "config-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
nom-supreme = "0.8.0"
tokio = { version = "1.17.0", features = ["full"] }
sis-core = { path = "../sis-core" }
cgmath = "0.18.0"

[dependencies.nom-locate]
git = "https://github.com/Calcoph/nom_locate"
